{
    "a" : [
    { "i" : "http://www.alltimerecordsstudios.com/Web_Ad_for_WLSK_Banner.jpg",
        "r" : "http://pn-assets-development.s3.amazonaws.com/manual/m1r.png",
        "x" : "Play this game!",
        "t" : "http://www.grio.com",
        "s" : "http://ads.b.playnomics.net/v1/impression?i=1&a=1&b=123457890",
        "f" : "http://redir.b.playnomics.net/v1/flag?i=1&a=1&b=1234567890",
        "d" : "http://ads.b.playnomics.net/v1/close?i=1&a=1&b=1234567890" },
    { "i" : "http://pn-assets-development.s3.amazonaws.com/manual/m2p.jpg",
        "r" : "http://pn-assets-development.s3.amazonaws.com/manual/m2r.jpg",
        "x" : "This game is better",
        "t" : "pna://changeBackground",
        "u" : "http://ads.b.playnomics.net/v1/click?i=2&a=1&b=123457890",
        "v" : "http://ads.b.playnomics.net/v1/clickPost?i=2&a=1&b=123457890",
        "s" : "http://ads.b.playnomics.net/v1/impression?i=2&a=1&b=123457890",
        "f" : "http://redir.b.playnomics.net/v1/flag?i=2&a=1&b=1234567890",
        "d" : "http://ads.b.playnomics.net/v1/close?i=2&a=1&b=1234567890" },
    { "i" : "http://pn-assets-development.s3.amazonaws.com/manual/m3p.gif",
        "r" : "http://pn-assets-development.s3.amazonaws.com/manual/m3r.gif",
        "x" : "This is the very best you’ll ever see",
        "t" : "pna://showBox();",
        "u" : "http://ads.b.playnomics.net/v1/click?i=3&a=1&b=123457890",
        "v" : "http://ads.b.playnomics.net/v1/clickPost?i=3&a=1&b=123457890",
        "s" : "http://ads.b.playnomics.net/v1/impression?i=3&a=1&b=123457890",
        "f" : "http://redir.b.playnomics.net/v1/flag?i=3&a=1&b=1234567890",
        "d" : "http://ads.b.playnomics.net/v1/close?i=3&a=1&b=1234567890" }],
    "l" :
    { "x" : 15,
      "y" : 15,
      "h" : 90,
      "w" : 480 },
    "b" :
    { "i" : "http://a.dryicons.com/files/graphics_previews/so_70s_background.jpg",
      "l" :
      { "x" : 100,
        "y" : 590 },
      "p" :
      { "x" : 100,
        "y" : 590 },
      "h" : 120,
      "w" : 510 },
    "c" :
    { "i" : "http://www.cocreatech.dk/images/pl_close_button.png",
        "x" : 465,
        "y" : 0,
        "h" : 45,
        "w" : 45 },
    "e" : 600,
    "s" : "Ok",
    "m" : null
}
