#!/bin/bash
set -e
#set -x

FULLSCRIPT=$(which $0)
BIN_PATH=`dirname ${FULLSCRIPT}`
TARGET_PATH=${BIN_PATH}/../target/Playnomics

XCODE5="/Applications/Xcode5.app/Contents/Developer/usr/bin/xcodebuild"

SRC_PATH=${BIN_PATH}/../src

FILE_NAME="libPlaynomicsSDK.a"
FINAL_FILE_NAME=${TARGET_PATH}/libPlaynomics.a

SYMROOT="build"

RELEASE_DEVICE_ARMV7_DIR=build/Release-iphoneos-armv7
RELEASE_SIMULATOR_DIR=build/Release-iphonesimulator

DEVICE=iphoneos7.0
SIMULATOR=iphonesimulator7.0

LOG_PATH=${BIN_PATH}/build.log

if [ -d "$TARGET_PATH" ]; then
    echo "Cleaning out old target directory"
    rm -r ${TARGET_PATH}
fi
mkdir ${TARGET_PATH}

echo "Starting build for iOS SDK. Log file for xcodebuild is ${LOG_PATH}"

echo "Building for arm7, arm7s"

${XCODE5} -project ${SRC_PATH}/PlaynomicsSDK.xcodeproj -configuration Release -target PlaynomicsSDK -sdk ${DEVICE} clean build RUN_CLANG_STATIC_ANALYZER=NO CONFIGURATION_BUILD_DIR=${RELEASE_DEVICE_ARMV7_DIR} ONLY_ACTIVE_ARCH=NO ARCHS="armv7 armv7s" >> ${LOG_PATH}

echo "Building for i386"

${XCODE5} -project ${SRC_PATH}/PlaynomicsSDK.xcodeproj -configuration Release -target PlaynomicsSDK -sdk ${SIMULATOR} clean build RUN_CLANG_STATIC_ANALYZER=NO CONFIGURATION_BUILD_DIR=${RELEASE_SIMULATOR_DIR} ONLY_ACTIVE_ARCH=NO ARCHS="i386" >> ${LOG_PATH}

echo "Merging build libraries into ${FINAL_FILE_NAME}"

echo "ARM7 Source Library ${SRC_PATH}/${RELEASE_DEVICE_ARMV7_DIR}/${FILE_NAME}"
echo "i386 Source Library ${SRC_PATH}/${RELEASE_SIMULATOR_DIR}/${FILE_NAME}"

lipo -create -output "${FINAL_FILE_NAME}" "${SRC_PATH}/${RELEASE_DEVICE_ARMV7_DIR}/${FILE_NAME}" "${SRC_PATH}/${RELEASE_SIMULATOR_DIR}/${FILE_NAME}"

cp ${SRC_PATH}/PlaynomicsSDK/Playnomics.h ${TARGET_PATH}
cp ${SRC_PATH}/PlaynomicsSDK/PNLogger.h ${TARGET_PATH}
